version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - 15534:5432

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
